### ISSUE TITLE
Compile with different pixel types?

### ISSUE THREAD

**Issue by NHPatterson** [InsightSoftwareConsortium/ITKElastix#137]
Is it possible to compile the wrapped elastix to support pixel types other than `float32`? I do a lot of registration with very large microscopy planes and having just an unsigned short pixel type would save a lot of memory. I'm happy to try things out on my end if anyone could point me to the relevant code.. 

Thanks!

**Comment by Svdvoort** [comment]
I agree that having `ITKElastix` also be compiled with `short` pixel type by default would be very helpful, and would also keep it in line with the Elastix binary. Right now this leads to problems since `ITKElastix` and the `Elastix` binary are compiled with different pixel types, and I feel like it would be most natural to at least have the same pixel types available in both compilations.

**Comment by thewtex** [comment]
If I recall correctly, the current limitation of `float32` wrapping is due to a mismatch between the interface classes and Elastix's internal mapping classes. @N-Dekker do you know if there has been progress on this?

xref: https://github.com/SuperElastix/elastix/issues/322

Once we update to the latest Elastix development version, should we be able to enable wrapping for these other types?

**Comment by N-Dekker** [comment]
@thewtex Do I understand correctly that the effect of the wrapping below is to support both float and double as input pixel type (but no other types)?

https://github.com/InsightSoftwareConsortium/ITKElastix/blob/c36279f04ded427d90d45ac2731e8119647c6c23/wrapping/itkElastixRegistrationMethod.wrap#L1-L2

https://github.com/InsightSoftwareConsortium/ITKElastix/blob/c36279f04ded427d90d45ac2731e8119647c6c23/wrapping/itkElastixRegistrationMethod.wrap#L1-L2

**Comment by dzenanz** [comment]
I know that float type is supported by default. I never tried double. Other types are not supported (UC, SS, etc). That seems like the relevant specification. I will let Matt answer. Meanwhile, you could try adding all scalar types there and build it locally.

**Comment by thewtex** [comment]
> Do I understand correctly that the effect of the wrapping below is to support both float and double as input pixel type (but no other types)?

Yes, correct. However, this would also need to be addressed: https://github.com/InsightSoftwareConsortium/ITKElastix/issues/137#issuecomment-1280888071

**Comment by N-Dekker** [comment]
Can you please tell me, how is the `itk.elastix_registration_method` defined exactly? In Python, `help(itk.elastix_registration_method)` tells me the following:

> Help on function elastix_registration_method in module itk.itkElastixRegistrationMethodPython:
>
> elastix_registration_method(*args, fixed_image: 'itk.Image' = Ellipsis, moving_image: 'itk.Image' = Ellipsis, fixed_mask: 'itk.Image' = Ellipsis, moving_mask: 'itk.Image' = Ellipsis, parameter_object=Ellipsis, initial_transform_parameter_file_name: str = Ellipsis, fixed_point_set_file_name: str = Ellipsis, moving_point_set_file_name: str = Ellipsis, output_directory: str = Ellipsis, log_file_name: str = Ellipsis, log_to_console: bool = Ellipsis, log_to_file: bool = Ellipsis, number_of_threads: int = Ellipsis, **kwargs) -> ...]]
    Proxy of C++ itkElastixRegistrationMethodIF2IF2 class.

What does the postfix "IF2IF2" of `itkElastixRegistrationMethodIF2IF2` mean? But more interestingly, how does the function body of `elastix_registration_method` look like?

**Comment by dzenanz** [comment]
Postfix "IF2IF2" means that it is instantiated with those template parameters, e.g. `itkElastixRegistrationMethodIF2IF2` == `itk::ElastixRegistrationMethod<<itk::Image<float,2>, itk::Image<float,2>>`.

If you look at `itkElastixRegistrationMethodPython.cpp` (on my computer found in  `M:\a\ITKElastix-py\Wrapping\Modules\Elastix\`) and `itkElastixRegistrationMethodPython.py` (in `M:\a\ITK-py\Wrapping\Generators\Python\itk\`) you will find some auto-generated plumbing which invokes stuff compiled from C++ into DLLs.

**Comment by N-Dekker** [comment]
Thanks @dzenanz So does that mean that by definition, the Python `itk.elastix_registration_method` function only supports a single image type, no matter how much we tweak itkElastixRegistrationMethod.wrap, the elastix CMake build config or whatever?  Or could this Python function also be extended to support multiple image types?

**Comment by dzenanz** [comment]
Yes, the tip of the iceberg of manual specification is https://github.com/InsightSoftwareConsortium/ITKElastix/blob/c36279f04ded427d90d45ac2731e8119647c6c23/wrapping/itkElastixRegistrationMethod.wrap. Even https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Registration/Common/wrapping/itkImageRegistrationMethod.wrap is quite simple, too. A bit more convoluted is https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageGrid/wrapping/itkResampleImageFilter.wrap. And the above mentioned [file from ITKUltrasound](https://github.com/KitwareMedical/ITKUltrasound/blob/v0.6.1/wrapping/itkCurvilinearArraySpecialCoordinatesImageFilters.wrap) is a monster.

**Comment by N-Dekker** [comment]
> Yes, the tip of the iceberg of manual specification is https://github.com/InsightSoftwareConsortium/ITKElastix/blob/c36279f04ded427d90d45ac2731e8119647c6c23/wrapping/itkElastixRegistrationMethod.wrap

Thanks, but isn't `itk_wrap_image_filter` only just instantiating the requested templates? Sorry, I still don't see how it would create the `elastix_registration_method` function.

**Comment by dzenanz** [comment]
ITK's general pythonication functionality turn any class in CamelCaseStyle into a function camel_case_style, and transforms the code into a series of instantiation, method calls (SetInput, SetX, SetY), Update(), and GetOutput().

Also take a look at [Wrapping section](https://itk.org/ITKSoftwareGuide/html/Book1/ITKSoftwareGuide-Book1ch9.html#x55-1520009.5).

**Comment by N-Dekker** [comment]
OK, thanks, I think I finally starts to understand a little bit! So ITKElastix instantiates itkElastixRegistrationMethod for both `float` and `double`, at https://github.com/InsightSoftwareConsortium/ITKElastix/blob/c36279f04ded427d90d45ac2731e8119647c6c23/wrapping/itkElastixRegistrationMethod.wrap#L1-L2  Does it also specify `float;double` as CMake variables ELASTIX_IMAGE_2D_PIXEL_TYPES, ELASTIX_IMAGE_3D_PIXEL_TYPES, and ELASTIX_IMAGE_4D_PIXEL_TYPES, when doing a CMake configure of elastix? Otherwise elastix still won't instantiate the components (C++ templates) for those pixel types.

**Comment by dzenanz** [comment]
I believe such options would go into https://github.com/InsightSoftwareConsortium/ITKElastix/blob/main/CMakeLists.txt. As I don't see them there, I assume they are on by default.
