### ISSUE TITLE
How to change Elastix version

### ISSUE THREAD

**Issue by MartinKjunior** [InsightSoftwareConsortium/ITKElastix#206]
When I installed ITK-elastix it came with version 5.1.0 which seems to have changed something about the way things are registered and I cannot get the same output as with an earlier version of elastix. Is there a way to change the elastix version ITK-elastix uses?

**Comment by ntatsisk** [comment]
Hi @MartinKjunior, 

you cannot actually change the version of `elastix` that a specific version of `itk-elastix` uses (except if you build it on your own). It also wouldn't make much sense because itk-elastix is just a wrapper that translates the C++ code in python, and all the functionality lives in the C++ elastix side. What might be easier to do is to use an older `itk-elastix` version instead.

As a side note it is generaly advised to use a environment manager like `conda` or `virtualenv`. Then in a fresh environment, you can do:

`python -m pip install itk-elastix==0.16.0`, OR `python -m pip install itk-elastix==0.15.0` etc.

You can find all available versions here: https://github.com/InsightSoftwareConsortium/ITKElastix/releases

**Comment by MartinKjunior** [comment]
Makes sense. Thanks
