### ISSUE TITLE
Is the log file really closed?

### ISSUE THREAD

**Issue by drchrisch** [InsightSoftwareConsortium/ITKElastix#61]
Hi,
I got the impression that the log file generated from running (Windows10, jupyter notebook)

result_image, result_transform_parameters = itk.elastix_registration_method(
    fixed, moving,
    ...
    log_to_console=False,
    **log_to_file=True**,
    ...)

is not really closed after finishing registration. Is this a known issue or did I forget to add some code?

**Comment by dzenanz** [comment]
Did you solve the problem? What was the solution?

**Comment by drchrisch** [comment]
Yes and no. It seems that itkelastix currently is a work-in-progress version that is well worth to follow but still uses some odd commands (see setup for ElastixRegistrationMethod/itkTransformixFilterPython). A really useful tool is the setParameter function. For the log file, there is basically no urgent need to write a log file if the parameters are well set. However, it is helpful during optimization and screening the log file is more comfortable than screening the output to the command window. This has not been settled yet.

**Comment by N-Dekker** [comment]
@drchrisch @dzenanz This issue should be fixed with pull request https://github.com/SuperElastix/elastix/pull/303 ("BUG: Close output streams at the end of GenerateData()"), merged to the elastix develop branch with commit https://github.com/SuperElastix/elastix/commit/18405304d97ae3c1af4d4e5224b938a6ef44b835 ("BUG: Use xoutManager (6 x) to make sure the output streams are closed")

Please have a try  😃
